/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaiduSearchIcon: typeof import('./components/icons/BaiduSearchIcon.vue')['default']
    BingSearchIcon: typeof import('./components/icons/BingSearchIcon.vue')['default']
    DropdownAction: typeof import('./components/layouts/DropdownAction.vue')['default']
    DuckduckgoSearchIcon: typeof import('./components/icons/DuckduckgoSearchIcon.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElText: typeof import('element-plus/es')['ElText']
    GoogleSearchIcon: typeof import('./components/icons/GoogleSearchIcon.vue')['default']
    Hitokoto: typeof import('./components/layouts/Hitokoto.vue')['default']
    SiteNavCard: typeof import('./components/layouts/SiteNavCard.vue')['default']
    SiteNavCopyright: typeof import('./components/layouts/SiteNavCopyright.vue')['default']
    SiteNavHeader: typeof import('./components/layouts/SiteNavHeader.vue')['default']
    SiteNavIcon: typeof import('./components/icons/SiteNavIcon.vue')['default']
    SiteNavMain: typeof import('./components/layouts/SiteNavMain.vue')['default']
    SiteNavSearch: typeof import('./components/layouts/SiteNavSearch.vue')['default']
    SiteNavSide: typeof import('./components/layouts/SiteNavSide.vue')['default']
    SVGIcon: typeof import('./components/svg/SVGIcon.vue')['default']
    TagIcon: typeof import('./components/icons/TagIcon.vue')['default']
    WebSites: typeof import('./components/layouts/WebSites.vue')['default']
  }
}
